# Generated by Django 4.1 on 2024-06-09 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fruit_name", models.CharField(max_length=50)),
                ("fruit_day_plus", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Origin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_location", models.CharField(max_length=200)),
                ("origin_address", models.CharField(max_length=200)),
                ("origin_longitude", models.CharField(default=0, max_length=100)),
                ("origin_latitude", models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warehouse_name", models.CharField(max_length=100)),
                ("warehouse_longitude", models.CharField(max_length=100)),
                ("warehouse_latitude", models.CharField(max_length=100)),
                ("warehouse_address", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehousing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehousing_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("warehousing_quantity", models.IntegerField(default=0)),
                (
                    "release_until",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("warehousing_price", models.IntegerField(default=0)),
                (
                    "barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.barcode",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Shipping_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("Shipping_quantity", models.IntegerField(default=0)),
                ("Shipping_price", models.IntegerField(default=0)),
                (
                    "barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.barcode",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inventory_quantity", models.IntegerField(default=0)),
                (
                    "fruit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.fruit",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.warehouse",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="barcode",
            name="fruit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.fruit"
            ),
        ),
        migrations.AddField(
            model_name="barcode",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.origin"
            ),
        ),
    ]
