# Generated by Django 4.1 on 2024-06-11 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                ("barcode_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Fruit",
            fields=[
                ("fruit_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fruit_name", models.CharField(max_length=50)),
                ("fruit_day_plus", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "inventory_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("inventory_quantity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Origin",
            fields=[
                ("origin_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("origin_location", models.CharField(max_length=200)),
                ("origin_address", models.CharField(max_length=200)),
                ("origin_longitude", models.CharField(max_length=200)),
                ("origin_latitude", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                ("shipping_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "Shipping_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("Shipping_quantity", models.IntegerField(default=0)),
                ("Shipping_price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "warehouse_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("warehouse_name", models.CharField(max_length=100)),
                ("warehouse_longitude", models.CharField(max_length=100)),
                ("warehouse_latitude", models.CharField(max_length=100)),
                ("warehouse_address", models.CharField(max_length=200)),
                ("warehouse_capacity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Warehousing",
            fields=[
                (
                    "warehousing_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "warehousing_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("warehousing_quantity", models.IntegerField(default=0)),
                (
                    "warehousing_until",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("warehousing_price", models.IntegerField(default=0)),
                (
                    "barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.barcode",
                    ),
                ),
            ],
        ),
    ]
