# Generated by Django 4.1 on 2024-06-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="barcode_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
